package xyz.wienerlabs.rasad.islam

data class SourceText(
    val key: String,
    val arabic: String?,
    val meaning: String,
    val citation: String,
    val shortCitation: String,
    val grade: String? = null,
    val translator: String? = null,
    val transliteration: String? = null,
)

object IslamicTexts {
    private const val DIYANET = "meal: Diyanet İşleri"
    private const val RASAD = "çeviri: Rasad"

    private val all: Map<String, SourceText> = listOf(
        SourceText(
            key = "2:144",
            arabic = "قَدْ نَرَىٰ تَقَلُّبَ وَجْهِكَ فِي السَّمَاءِ ۖ فَلَنُوَلِّيَنَّكَ قِبْلَةً تَرْضَاهَا ۚ فَوَلِّ وَجْهَكَ شَطْرَ الْمَسْجِدِ الْحَرَامِ ۚ وَحَيْثُ مَا كُنْتُمْ فَوَلُّوا وُجُوهَكُمْ شَطْرَهُ ۗ وَإِنَّ الَّذِينَ أُوتُوا الْكِتَابَ لَيَعْلَمُونَ أَنَّهُ الْحَقُّ مِنْ رَبِّهِمْ ۗ وَمَا اللَّهُ بِغَافِلٍ عَمَّا يَعْمَلُونَ",
            meaning = "Yüzünü göğe çevirip durduğunu görüyoruz. Hoşnud olacağın kıbleye seni elbette çevireceğiz. Artık yüzünü Mescid-i Haram semtine çevir; bulunduğunuz yerde yüzlerinizi o yöne çevirin. Doğrusu Kitap verilenler, bunun Rab'lerinden bir gerçek olduğunu bilirler. Allah onların yaptıklarından gafil değildir.",
            citation = "Kur'an, Bakara 2:144",
            shortCitation = "Bakara 2:144",
            translator = DIYANET,
        ),
        SourceText(
            key = "2:185",
            arabic = "شَهْرُ رَمَضَانَ الَّذِي أُنْزِلَ فِيهِ الْقُرْآنُ هُدًى لِلنَّاسِ وَبَيِّنَاتٍ مِنَ الْهُدَىٰ وَالْفُرْقَانِ ۚ فَمَنْ شَهِدَ مِنْكُمُ الشَّهْرَ فَلْيَصُمْهُ ۖ وَمَنْ كَانَ مَرِيضًا أَوْ عَلَىٰ سَفَرٍ فَعِدَّةٌ مِنْ أَيَّامٍ أُخَرَ ۗ يُرِيدُ اللَّهُ بِكُمُ الْيُسْرَ وَلَا يُرِيدُ بِكُمُ الْعُسْرَ وَلِتُكْمِلُوا الْعِدَّةَ وَلِتُكَبِّرُوا اللَّهَ عَلَىٰ مَا هَدَاكُمْ وَلَعَلَّكُمْ تَشْكُرُونَ",
            meaning = "Ramazan ayı, ki onda Kuran, insanlara yol gösterici ve doğruyu yanlıştan ayırıcı belgeler olarak indirildi. Sizden bu ayı idrak eden, onda oruç tutsun; hasta veya yolculukta olan, tutamadığı günlerin sayısınca diğer günlerde tutsun. Allah size kolaylık ister, zorluk istemez. Bu kolaylıkları, sayıyı tamamlamanız ve size yol gösterdiğine karşılık O'nu ululamanız için meşru kılmıştır; ola ki şükredersiniz.",
            citation = "Kur'an, Bakara 2:185",
            shortCitation = "Bakara 2:185",
            translator = DIYANET,
        ),
        SourceText(
            key = "2:189",
            arabic = "۞ يَسْأَلُونَكَ عَنِ الْأَهِلَّةِ ۖ قُلْ هِيَ مَوَاقِيتُ لِلنَّاسِ وَالْحَجِّ ۗ وَلَيْسَ الْبِرُّ بِأَنْ تَأْتُوا الْبُيُوتَ مِنْ ظُهُورِهَا وَلَٰكِنَّ الْبِرَّ مَنِ اتَّقَىٰ ۗ وَأْتُوا الْبُيُوتَ مِنْ أَبْوَابِهَا ۚ وَاتَّقُوا اللَّهَ لَعَلَّكُمْ تُفْلِحُونَ",
            meaning = "Sana hilal halindeki ayları sorarlar. De ki: \"Onlar, insanların ve hac vakitlerinin ölçüsüdür\". Evlere arkalarından girmeniz iyilik değildir; iyi kimse kötülükten sakınan kimsedir. Evlere kapılarından girin; Allah'tan sakının ki muradınıza erersiniz.",
            citation = "Kur'an, Bakara 2:189",
            shortCitation = "Bakara 2:189",
            translator = DIYANET,
        ),
        SourceText(
            key = "4:103",
            arabic = "فَإِذَا قَضَيْتُمُ الصَّلَاةَ فَاذْكُرُوا اللَّهَ قِيَامًا وَقُعُودًا وَعَلَىٰ جُنُوبِكُمْ ۚ فَإِذَا اطْمَأْنَنْتُمْ فَأَقِيمُوا الصَّلَاةَ ۚ إِنَّ الصَّلَاةَ كَانَتْ عَلَى الْمُؤْمِنِينَ كِتَابًا مَوْقُوتًا",
            meaning = "Namazı kıldıktan başka, Allah'ı ayakta iken, otururken, yan yatarken de anın. Emniyete kavuştuğunuzda, namazı gereğince kılın. Namaz şüphesiz, inananlara belirli vakitlerde farz kılınmıştır.",
            citation = "Kur'an, Nisâ 4:103",
            shortCitation = "Nisâ 4:103",
            translator = DIYANET,
        ),
        SourceText(
            key = "6:97",
            arabic = "وَهُوَ الَّذِي جَعَلَ لَكُمُ النُّجُومَ لِتَهْتَدُوا بِهَا فِي ظُلُمَاتِ الْبَرِّ وَالْبَحْرِ ۗ قَدْ فَصَّلْنَا الْآيَاتِ لِقَوْمٍ يَعْلَمُونَ",
            meaning = "O, yıldızları kara ve denizin karanlıklarında yol bulasınız diye sizin için var edendir. Bilen millet için ayetleri uzun uzadıya açıkladık.",
            citation = "Kur'an, En'âm 6:97",
            shortCitation = "En'âm 6:97",
            translator = DIYANET,
        ),
        SourceText(
            key = "9:36",
            arabic = "إِنَّ عِدَّةَ الشُّهُورِ عِنْدَ اللَّهِ اثْنَا عَشَرَ شَهْرًا فِي كِتَابِ اللَّهِ يَوْمَ خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ مِنْهَا أَرْبَعَةٌ حُرُمٌ ۚ ذَٰلِكَ الدِّينُ الْقَيِّمُ ۚ فَلَا تَظْلِمُوا فِيهِنَّ أَنْفُسَكُمْ ۚ وَقَاتِلُوا الْمُشْرِكِينَ كَافَّةً كَمَا يُقَاتِلُونَكُمْ كَافَّةً ۚ وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ",
            meaning = "Allah'ın gökleri ve yeri yarattığı günkü yazısında, Allah'a göre ayların sayısı onikidir. Bunlardan dördü hürmetli aydır. Bu dosdoğru bir nizamdır. Öyleyse o aylar içinde kendinize yazık etmeyin, topyekun sizinle savaşan putperestlerle siz de topyekun savaşın, Allah'ın sakınanlarla beraber olduğunu bilin.",
            citation = "Kur'an, Tevbe 9:36",
            shortCitation = "Tevbe 9:36",
            translator = DIYANET,
        ),
        SourceText(
            key = "10:5",
            arabic = "هُوَ الَّذِي جَعَلَ الشَّمْسَ ضِيَاءً وَالْقَمَرَ نُورًا وَقَدَّرَهُ مَنَازِلَ لِتَعْلَمُوا عَدَدَ السِّنِينَ وَالْحِسَابَ ۚ مَا خَلَقَ اللَّهُ ذَٰلِكَ إِلَّا بِالْحَقِّ ۚ يُفَصِّلُ الْآيَاتِ لِقَوْمٍ يَعْلَمُونَ",
            meaning = "Güneşi ışıklı ve ayı nurlu yapan; yılların sayısını ve hesabı bilmeniz için, aya konak yerleri düzenleyen O'dur. Allah bunları ancak gerçeğe göre yaratmıştır; bilen millete ayetleri uzun uzadıya açıklıyor.",
            citation = "Kur'an, Yûnus 10:5",
            shortCitation = "Yûnus 10:5",
            translator = DIYANET,
        ),
        SourceText(
            key = "16:16",
            arabic = "وَعَلَامَاتٍ ۚ وَبِالنَّجْمِ هُمْ يَهْتَدُونَ",
            meaning = "… işaretler meydana getirmiştir. Onlar yıldızla da yollarını bulurlar.",
            citation = "Kur'an, Nahl 16:16",
            shortCitation = "Nahl 16:16",
            translator = DIYANET + " (15. âyetle birlikte verilen mealden)",
        ),
        SourceText(
            key = "53:49",
            arabic = "وَأَنَّهُ هُوَ رَبُّ الشِّعْرَىٰ",
            meaning = "Doğrusu Şira yıldızının Rabbi O'dur.",
            citation = "Kur'an, Necm 53:49",
            shortCitation = "Necm 53:49",
            translator = DIYANET,
        ),
        SourceText(
            key = "67:5",
            arabic = "وَلَقَدْ زَيَّنَّا السَّمَاءَ الدُّنْيَا بِمَصَابِيحَ وَجَعَلْنَاهَا رُجُومًا لِلشَّيَاطِينِ ۖ وَأَعْتَدْنَا لَهُمْ عَذَابَ السَّعِيرِ",
            meaning = "And olsun ki, yakın göğü kandillerle donattık, onları şeytanlar için taşlamalar yaptık ve şeytanlara çılgın alev azabını hazırladık.",
            citation = "Kur'an, Mülk 67:5",
            shortCitation = "Mülk 67:5",
            translator = DIYANET,
        ),
        SourceText(
            key = "bukhari:1909",
            arabic = "صُومُوا لِرُؤْيَتِهِ، وَأَفْطِرُوا لِرُؤْيَتِهِ، فَإِنْ غُبِّيَ عَلَيْكُمْ فَأَكْمِلُوا عِدَّةَ شَعْبَانَ ثَلاَثِينَ",
            meaning = "Onu (hilali) görünce oruç tutun, onu görünce orucu bırakın. Size gizli kalırsa (göremezseniz) Şaban'ın sayısını otuza tamamlayın.",
            citation = "Buhârî, 1909",
            shortCitation = "Buhârî 1909",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "bukhari:846",
            arabic = "أَصْبَحَ مِنْ عِبَادِي مُؤْمِنٌ بِي وَكَافِرٌ، فَأَمَّا مَنْ قَالَ مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ فَذَلِكَ مُؤْمِنٌ بِي وَكَافِرٌ بِالْكَوْكَبِ، وَأَمَّا مَنْ قَالَ بِنَوْءِ كَذَا وَكَذَا فَذَلِكَ كَافِرٌ بِي وَمُؤْمِنٌ بِالْكَوْكَبِ",
            meaning = "(Allah buyurdu ki:) Kullarımdan kimi bana inanan, kimi de inkâr eden olarak sabahladı. ‘Allah'ın lütfu ve rahmetiyle yağmura kavuştuk’ diyen bana inanmış, yıldızı inkâr etmiştir. ‘Falan falan yıldızın nev'iyle (doğup batmasıyla)’ diyen ise beni inkâr etmiş, yıldıza inanmıştır.",
            citation = "Buhârî, 846 · hadis-i kudsî",
            shortCitation = "Buhârî 846",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "qatada",
            arabic = "وَقَالَ قَتَادَةُ: {وَلَقَدْ زَيَّنَّا السَّمَاءَ الدُّنْيَا بِمَصَابِيحَ} خَلَقَ هَذِهِ النُّجُومَ لِثَلاَثٍ، جَعَلَهَا زِينَةً لِلسَّمَاءِ، وَرُجُومًا لِلشَّيَاطِينِ، وَعَلاَمَاتٍ يُهْتَدَى بِهَا، فَمَنْ تَأَوَّلَ فِيهَا بِغَيْرِ ذَلِكَ أَخْطَأَ وَأَضَاعَ نَصِيبَهُ، وَتَكَلَّفَ مَا لاَ عِلْمَ لَهُ بِهِ.",
            meaning = "Katâde, ‘Andolsun ki, yakın göğü kandillerle donattık’ âyeti hakkında dedi ki: Allah bu yıldızları üç şey için yarattı: Onları göğe süs, şeytanlara atılan taşlar ve kendileriyle yol bulunan işaretler kıldı. Kim onlara bundan başka bir anlam yüklerse yanılmış, nasibini yitirmiş ve hakkında bilgisi olmayan bir işe kalkışmış olur.",
            citation = "Katâde'nin sözü (maktû') · Buhârî, Bed'ü'l-halk kitabı, Nücûm bâbının başında isnadsız (ta'lîkan)",
            shortCitation = "Katâde (Buhârî)",
            translator = RASAD,
        ),
        SourceText(
            key = "tirmidhi:3451",
            arabic = "اللَّهُمَّ أَهْلِلْهُ عَلَيْنَا بِالْيُمْنِ وَالإِيمَانِ وَالسَّلاَمَةِ وَالإِسْلاَمِ رَبِّي وَرَبُّكَ اللَّهُ",
            meaning = "Allah'ım! Onu üzerimize bereket ve iman, esenlik ve İslam ile doğdur. (Ey hilal!) Benim Rabbim de senin Rabbin de Allah'tır.",
            citation = "Tirmizî, 3451",
            shortCitation = "Tirmizî 3451",
            grade = "Tirmizî: hasen garîb · Elbânî: yollarının toplamıyla sahih · Dârüsselâm: zayıf",
            translator = RASAD,
            transliteration = "Allâhümme ehlilhü aleynâ bi'l-yümni ve'l-îmân, ve's-selâmeti ve'l-İslâm. Rabbî ve Rabbüke'llâh.",
        ),
        SourceText(
            key = "bukhari:1044",
            arabic = "إِنَّ الشَّمْسَ وَالْقَمَرَ آيَتَانِ مِنْ آيَاتِ اللَّهِ، لاَ يَنْخَسِفَانِ لِمَوْتِ أَحَدٍ وَلاَ لِحَيَاتِهِ، فَإِذَا رَأَيْتُمْ ذَلِكَ فَادْعُوا اللَّهَ وَكَبِّرُوا، وَصَلُّوا وَتَصَدَّقُوا",
            meaning = "Güneş ve Ay, Allah'ın âyetlerinden iki âyettir; kimsenin ölümü ya da hayatı sebebiyle tutulmazlar. Bunu gördüğünüzde Allah'a dua edin, tekbir getirin, namaz kılın ve sadaka verin.",
            citation = "Buhârî, 1044",
            shortCitation = "Buhârî 1044",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "muslim:1094",
            arabic = "لاَ يَغُرَّنَّكُمْ مِنْ سَحُورِكُمْ أَذَانُ بِلاَلٍ وَلاَ بَيَاضُ الأُفُقِ الْمُسْتَطِيلُ هَكَذَا حَتَّى يَسْتَطِيرَ هَكَذَا. وَحَكَاهُ حَمَّادٌ بِيَدَيْهِ قَالَ يَعْنِي مُعْتَرِضًا.",
            meaning = "Bilâl'in ezanı da, ufuktaki şöyle uzanan beyazlık da sizi sahurunuz konusunda yanıltmasın; ta ki (aydınlık) şöyle yayılıncaya kadar. Râvi Hammâd bunu elleriyle gösterdi; yani yatay olarak.",
            citation = "Müslim, 1094c",
            shortCitation = "Müslim 1094",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "muslim:1162",
            arabic = "صِيَامُ يَوْمِ عَرَفَةَ أَحْتَسِبُ عَلَى اللَّهِ أَنْ يُكَفِّرَ السَّنَةَ الَّتِي قَبْلَهُ وَالسَّنَةَ الَّتِي بَعْدَهُ وَصِيَامُ يَوْمِ عَاشُورَاءَ أَحْتَسِبُ عَلَى اللَّهِ أَنْ يُكَفِّرَ السَّنَةَ الَّتِي قَبْلَهُ",
            meaning = "Arefe günü orucunun, önceki yılın ve sonraki yılın günahlarına kefaret olmasını Allah'tan umarım. Âşûrâ günü orucunun da önceki yılın günahlarına kefaret olmasını Allah'tan umarım.",
            citation = "Müslim, 1162a (hadisin bir bölümü)",
            shortCitation = "Müslim 1162",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "muslim:1134",
            arabic = "لَئِنْ بَقِيتُ إِلَى قَابِلٍ لأَصُومَنَّ التَّاسِعَ",
            meaning = "Gelecek yıla ulaşırsam, dokuzuncu günü mutlaka oruç tutacağım.",
            citation = "Müslim, 1134b",
            shortCitation = "Müslim 1134",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "muslim:1164",
            arabic = "مَنْ صَامَ رَمَضَانَ ثُمَّ أَتْبَعَهُ سِتًّا مِنْ شَوَّالٍ كَانَ كَصِيَامِ الدَّهْرِ",
            meaning = "Kim Ramazan orucunu tutar, ardından ona Şevval'den altı gün eklerse, sürekli oruç tutmuş gibi olur.",
            citation = "Müslim, 1164a",
            shortCitation = "Müslim 1164",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "tirmidhi:761",
            arabic = "يَا أَبَا ذَرٍّ إِذَا صُمْتَ مِنَ الشَّهْرِ ثَلاَثَةَ أَيَّامٍ فَصُمْ ثَلاَثَ عَشْرَةَ وَأَرْبَعَ عَشْرَةَ وَخَمْسَ عَشْرَةَ",
            meaning = "Ey Ebû Zer! Aydan üç gün oruç tutacaksan on üçüncü, on dördüncü ve on beşinci günleri tut.",
            citation = "Tirmizî, 761",
            shortCitation = "Tirmizî 761",
            grade = "Tirmizî: hasen · Elbânî: hasen sahih · Dârüsselâm: hasen",
            translator = RASAD,
        ),
        SourceText(
            key = "tirmidhi:757",
            arabic = "مَا مِنْ أَيَّامٍ الْعَمَلُ الصَّالِحُ فِيهِنَّ أَحَبُّ إِلَى اللَّهِ مِنْ هَذِهِ الأَيَّامِ الْعَشْرِ",
            meaning = "Salih amelin Allah katında bu on günden daha sevimli olduğu hiçbir gün yoktur.",
            citation = "Tirmizî, 757 (hadisin başı)",
            shortCitation = "Tirmizî 757",
            grade = "Tirmizî: hasen sahih garîb · Dârüsselâm: sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "bukhari:2017",
            arabic = "تَحَرَّوْا لَيْلَةَ الْقَدْرِ فِي الْوِتْرِ مِنَ الْعَشْرِ الأَوَاخِرِ مِنْ رَمَضَانَ",
            meaning = "Kadir Gecesi'ni Ramazan'ın son on gecesinin tek olanlarında arayın.",
            citation = "Buhârî, 2017",
            shortCitation = "Buhârî 2017",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "muslim:1141",
            arabic = "أَيَّامُ التَّشْرِيقِ أَيَّامُ أَكْلٍ وَشُرْبٍ",
            meaning = "Teşrik günleri yeme ve içme günleridir.",
            citation = "Müslim, 1141a",
            shortCitation = "Müslim 1141",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "tirmidhi:149",
            arabic = "أَمَّنِي جِبْرِيلُ عَلَيْهِ السَّلاَمُ عِنْدَ الْبَيْتِ مَرَّتَيْنِ فَصَلَّى الظُّهْرَ فِي الأُولَى مِنْهُمَا حِينَ كَانَ الْفَىْءُ مِثْلَ الشِّرَاكِ ثُمَّ صَلَّى الْعَصْرَ حِينَ كَانَ كُلُّ شَيْءٍ مِثْلَ ظِلِّهِ",
            meaning = "Cebrâil (aleyhisselâm) Beytullah'ın yanında bana iki kez imamlık yaptı. Birincisinde öğleyi, gölge ayakkabı bağı kadarken kıldırdı; sonra ikindiyi, her şeyin gölgesi kendi boyu kadar olduğunda kıldırdı.",
            citation = "Tirmizî, 149 (hadisin başı)",
            shortCitation = "Tirmizî 149",
            grade = "Tirmizî: hasen sahih · Elbânî: hasen sahih · Dârüsselâm: hasen",
            translator = RASAD,
        ),
        SourceText(
            key = "tirmidhi:149:fecr",
            arabic = "ثُمَّ صَلَّى الْفَجْرَ حِينَ بَرَقَ الْفَجْرُ وَحَرُمَ الطَّعَامُ عَلَى الصَّائِمِ",
            meaning = "Sonra sabah namazını, fecir doğup oruçluya yemek haram olduğunda kıldırdı.",
            citation = "Tirmizî, 149 (hadisin bir bölümü)",
            shortCitation = "Tirmizî 149 · fecir",
            grade = "Tirmizî: hasen sahih · Elbânî: hasen sahih · Dârüsselâm: hasen",
            translator = RASAD,
        ),
        SourceText(
            key = "abudawud:3905",
            arabic = "مَنِ اقْتَبَسَ عِلْمًا مِنَ النُّجُومِ اقْتَبَسَ شُعْبَةً مِنَ السِّحْرِ زَادَ مَا زَادَ",
            meaning = "Kim yıldızlardan bir ilim edinirse sihirden bir şube edinmiş olur; onu arttırdıkça bu da artar.",
            citation = "Ebû Dâvûd, 3905",
            shortCitation = "Ebû Dâvûd 3905",
            grade = "Elbânî: hasen",
            translator = RASAD,
        ),
        SourceText(
            key = "muslim:934",
            arabic = "أَرْبَعٌ فِي أُمَّتِي مِنْ أَمْرِ الْجَاهِلِيَّةِ لاَ يَتْرُكُونَهُنَّ الْفَخْرُ فِي الأَحْسَابِ وَالطَّعْنُ فِي الأَنْسَابِ وَالاِسْتِسْقَاءُ بِالنُّجُومِ وَالنِّيَاحَةُ",
            meaning = "Ümmetimde Câhiliye işlerinden dört şey vardır ki onları bırakmazlar: soylarla övünmek, soylara dil uzatmak, yağmuru yıldızlardan beklemek ve ölünün ardından feryat ederek ağlamak.",
            citation = "Müslim, 934 (hadisin bir bölümü)",
            shortCitation = "Müslim 934",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "hattabi",
            arabic = "علم النجوم المنهي عنه هو ما يدل عليه أهل التنجيم من علم الكوائن والحوادث التي لم تقع كمجيء الأمطار وتغير الأسعار وأما ما يعلم به أوقات الصلاة وجهة القبلة فغير داخل فيما نهي عنه",
            meaning = "Yasaklanan yıldız ilmi, müneccimlerin henüz olmamış olaylar ve hadiseler hakkında, yağmurların geleceği ya da fiyatların değişeceği gibi, haber verdikleri bilgidir. Namaz vakitlerinin ve kıble yönünün kendisiyle bilindiği ilim ise yasaklananın kapsamına girmez.",
            citation = "Hattâbî, Meâlimü's-sünen · Avnü'l-ma'bûd 10/319'daki aktarımla",
            shortCitation = "Hattâbî",
            translator = RASAD,
        ),
        SourceText(
            key = "uthaymin:ikiye",
            arabic = "عِلمُ النُّجومِ ينقَسِمُ إلى قِسمَينِ: 1- عِلمُ التأثيرِ. 2- عِلمُ التسييرِ.",
            meaning = "Yıldız ilmi iki kısma ayrılır: 1. Te'sîr (etki) ilmi. 2. Tesyîr (seyir) ilmi.",
            citation = "İbn Useymîn, el-Kavlü'l-müfîd 2/5 · Dürerü's-seniyye'deki aktarımla",
            shortCitation = "İbn Useymîn",
            translator = RASAD,
        ),
        SourceText(
            key = "uthaymin:tesyir",
            arabic = "الثَّاني: عِلمُ التسييرِ. وهذا ينقَسِمُ إلى قِسمَين: الأوَّلُ: أن يستَدِلَّ بسَيرِها على المصالحِ الدِّينيَّةِ؛ فهذا مطلوبٌ، وإذا كان يُعِينُ على مصالحَ دينيَّةٍ واجبةٍ كان تعَلُّمُها واجِبًا، كما لو أراد أن يستَدِلَّ بالنُّجومِ على جِهةِ القِبلةِ؛ فالنّجمُ الفلانيُّ يكونُ ثُلُثَ اللَّيلِ قِبلةً، والنَّجمُ الفُلانيُّ يكونُ ربُعَ اللَّيلِ قِبلةً؛ فهذا فيه فائدةٌ عظيمةٌ.",
            meaning = "İkincisi tesyîr ilmidir. Bu da iki kısma ayrılır. Birincisi, yıldızların seyrinden dinî maslahatlar için delil çıkarmaktır; bu istenen bir şeydir. Vacip olan dinî maslahatlara yardım ediyorsa onu öğrenmek vacip olur; yıldızlarla kıble yönünü bulmak istemek gibi: falan yıldız gecenin üçte birinde kıble yönündedir, falan yıldız gecenin dörtte birinde kıble yönündedir. Bunda büyük fayda vardır.",
            citation = "İbn Useymîn, el-Kavlü'l-müfîd 2/5 · Dürerü's-seniyye'deki aktarımla",
            shortCitation = "İbn Useymîn",
            translator = RASAD,
        ),
        SourceText(
            key = "abudawud:1134",
            arabic = "إِنَّ اللَّهَ قَدْ أَبْدَلَكُمْ بِهِمَا خَيْرًا مِنْهُمَا يَوْمَ الأَضْحَى وَيَوْمَ الْفِطْرِ",
            meaning = "Allah size (Câhiliye'de eğlendiğiniz) bu iki günün yerine onlardan daha hayırlısını verdi: Kurban Bayramı günü ve Ramazan Bayramı günü.",
            citation = "Ebû Dâvûd, 1134",
            shortCitation = "Ebû Dâvûd 1134",
            grade = "Elbânî: sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "bukhari:1990",
            arabic = "هَذَانِ يَوْمَانِ نَهَى رَسُولُ اللَّهِ صلى الله عليه وسلم عَنْ صِيَامِهِمَا يَوْمُ فِطْرِكُمْ مِنْ صِيَامِكُمْ، وَالْيَوْمُ الآخَرُ تَأْكُلُونَ فِيهِ مِنْ نُسُكِكُمْ",
            meaning = "(Ömer dedi ki:) Bu ikisi, Resûlullah'ın (s.a.v.) oruç tutmayı yasakladığı iki gündür: Orucunuzu bitirdiğiniz gün ve kurbanlarınızdan yediğiniz diğer gün.",
            citation = "Buhârî, 1990",
            shortCitation = "Buhârî 1990",
            grade = "Sahih",
            translator = RASAD,
        ),
        SourceText(
            key = "bukhari:3197",
            arabic = "الزَّمَانُ قَدِ اسْتَدَارَ كَهَيْئَتِهِ يَوْمَ خَلَقَ السَّمَوَاتِ وَالأَرْضَ، السَّنَةُ اثْنَا عَشَرَ شَهْرًا، مِنْهَا أَرْبَعَةٌ حُرُمٌ، ثَلاَثَةٌ مُتَوَالِيَاتٌ ذُو الْقَعْدَةِ وَذُو الْحِجَّةِ وَالْمُحَرَّمُ، وَرَجَبُ مُضَرَ الَّذِي بَيْنَ جُمَادَى وَشَعْبَانَ",
            meaning = "Zaman, Allah'ın gökleri ve yeri yarattığı gündeki hâline döndü. Yıl on iki aydır; bunlardan dördü haram aylardır. Üçü art arda gelir: Zilkade, Zilhicce ve Muharrem. (Dördüncüsü) Cemâzî ile Şaban arasındaki Mudar'ın Recebi'dir.",
            citation = "Buhârî, 3197",
            shortCitation = "Buhârî 3197",
            grade = "Sahih",
            translator = RASAD,
        ),
    ).associateBy { it.key }

    operator fun get(key: String): SourceText? = all[key]

    val keys: Set<String> get() = all.keys
}
