package xyz.wienerlabs.rasad.sky

object Constellations {
    private val turkishNames = mapOf(
        "And" to "Andromeda",
        "Ant" to "Hava Tulumbası",
        "Aps" to "Cennet Kuşu",
        "Aqr" to "Kova",
        "Aql" to "Kartal",
        "Ara" to "Sunak",
        "Ari" to "Koç",
        "Aur" to "Arabacı",
        "Boo" to "Çoban",
        "Cae" to "Oyma Kalemi",
        "Cam" to "Zürafa",
        "Cnc" to "Yengeç",
        "CVn" to "Av Köpekleri",
        "CMa" to "Büyük Köpek",
        "CMi" to "Küçük Köpek",
        "Cap" to "Oğlak",
        "Car" to "Karina",
        "Cas" to "Kassiopeia",
        "Cen" to "Erboğa",
        "Cep" to "Kefeus",
        "Cet" to "Balina",
        "Cha" to "Bukalemun",
        "Cir" to "Pergel",
        "Col" to "Güvercin",
        "Com" to "Berenis'in Saçı",
        "CrA" to "Güney Tacı",
        "CrB" to "Kuzey Tacı",
        "Crv" to "Karga",
        "Crt" to "Kupa",
        "Cru" to "Güney Haçı",
        "Cyg" to "Kuğu",
        "Del" to "Yunus",
        "Dor" to "Kılıçbalığı",
        "Dra" to "Ejderha",
        "Equ" to "Tay",
        "Eri" to "Irmak",
        "For" to "Fırın",
        "Gem" to "İkizler",
        "Gru" to "Turna",
        "Her" to "Herkül",
        "Hor" to "Saat",
        "Hya" to "Suyılanı",
        "Hyi" to "Küçük Suyılanı",
        "Ind" to "Hintli",
        "Lac" to "Kertenkele",
        "Leo" to "Aslan",
        "LMi" to "Küçük Aslan",
        "Lep" to "Tavşan",
        "Lib" to "Terazi",
        "Lup" to "Kurt",
        "Lyn" to "Vaşak",
        "Lyr" to "Çalgı",
        "Men" to "Masa Dağı",
        "Mic" to "Mikroskop",
        "Mon" to "Tekboynuz",
        "Mus" to "Sinek",
        "Nor" to "Gönye",
        "Oct" to "Oktant",
        "Oph" to "Yılancı",
        "Ori" to "Avcı",
        "Pav" to "Tavus",
        "Peg" to "Kanatlı At",
        "Per" to "Perseus",
        "Phe" to "Anka",
        "Pic" to "Ressam",
        "Psc" to "Balıklar",
        "PsA" to "Güney Balığı",
        "Pup" to "Pupa",
        "Pyx" to "Pusula",
        "Ret" to "Ağ",
        "Sge" to "Ok",
        "Sgr" to "Yay",
        "Sco" to "Akrep",
        "Scl" to "Heykeltıraş",
        "Sct" to "Kalkan",
        "Ser" to "Yılan",
        "Sex" to "Sekstant",
        "Tau" to "Boğa",
        "Tel" to "Teleskop",
        "Tri" to "Üçgen",
        "TrA" to "Güney Üçgeni",
        "Tuc" to "Tukan",
        "UMa" to "Büyük Ayı",
        "UMi" to "Küçük Ayı",
        "Vel" to "Yelken",
        "Vir" to "Başak",
        "Vol" to "Uçan Balık",
        "Vul" to "Tilki",
    )

    fun turkishName(code: String): String = turkishNames[code] ?: code

    val allCodes: Set<String> get() = turkishNames.keys
}
